events {}
http {
    upstream backend {
        server http_server_instance_1:3000;
        server http_server_instance_2:3000;
        server http_server_instance_3:3000;
    }
    server {
        listen 80;
        server_name load_balancer;

        location / {
            proxy_pass http://backend;
        }
    }
}